WITH CTE AS (
Select
--STARTED_AT,
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun') 
     THEN 'WEEKEND' 
     ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2) 
     THEN 'WINTER'   
     WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5) 
     THEN 'SPRING'
     WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8) 
     THEN 'SUMMER'
     WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (9,10,11) 
     THEN 'FALL'
     ELSE 'UNKNOWN'
END AS SEASON_OF_YEAR

From {{ source('demo','BIKE')}}
Where STARTED_AT <> 'started_at'
)

Select * from CTE


